figure(1)
plot(erropitch)
title('Erro de picada')
xlabel('t(s)')
ylabel('erro(rad)')
set(get(gca,'YLabel'),'Rotation',0)

figure(2)
plot(erroroll)
title('Erro de rolamento')
xlabel('t(s)')
ylabel('erro(rad)')
set(get(gca,'YLabel'),'Rotation',0)

figure(3)
plot(errox)
title('Erro de posição x')
xlabel('t(s)')
ylabel('erro(m)')
set(get(gca,'YLabel'),'Rotation',0)

figure(4)
plot(erroy)
title('Erro de posição y')
xlabel('t(s)')
ylabel('erro(m)')
set(get(gca,'YLabel'),'Rotation',0)

figure(5)
plot(erroyaw)
title('Erro de guinada')
xlabel('t(s)')
ylabel('erro(rad)')
set(get(gca,'YLabel'),'Rotation',0)

